from __future__ import annotations

import json
import time
from typing import Any

import requests

from config import GEMINI_API_KEY, GEMINI_MODEL, validate_config
from question import Question
from validators import ValidationError, validate_question

_GEMINI_URL = "https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent"

_RESPONSE_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        "questions": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "subject": {"type": "string"},
                    "exam": {"type": "string"},
                    "topic": {"type": "string"},
                    "difficulty": {"type": "string"},
                    "question": {"type": "string"},
                    "choices": {
                        "type": "array",
                        "items": {"type": "string"},
                        "minItems": 4,
                        "maxItems": 4,
                    },
                    "correct_choice_index": {"type": "integer", "minimum": 0, "maximum": 3},
                    "explanation": {"type": "string"},
                    "shortcut": {"type": ["string", "null"]},
                    "source_type": {"type": "string"},
                    "source_reference": {"type": ["string", "null"]},
                    "math_expression": {"type": ["string", "null"]},
                },
                "required": [
                    "subject",
                    "exam",
                    "topic",
                    "difficulty",
                    "question",
                    "choices",
                    "correct_choice_index",
                    "explanation",
                    "shortcut",
                    "source_type",
                    "source_reference",
                    "math_expression",
                ],
            },
        }
    },
    "required": ["questions"],
}


def generate_questions(
    *,
    subject: str,
    exam: str,
    topic: str,
    difficulty: str,
    count: int,
    language: str = "Hinglish",
) -> list[Question]:
    if count < 1:
        raise ValueError("count must be at least 1")
    validate_config(require_gemini=True)

    prompt = f"""
Create exactly {count} original competitive-exam practice questions.

Exam: {exam}
Subject: {subject}
Topic: {topic}
Difficulty: {difficulty}
Output language: {language}

Rules:
- Create original questions, not copied previous-year questions.
- Every question must have exactly one defensible correct answer.
- Every question must be fully self-contained in text. Never require an unseen figure, diagram, chart, image, table, map, or visual prompt.
- Do not refer to `given figure`, `shown below`, `in the diagram`, `from the image`, or any other missing visual. Describe all required information directly in the question.
- Every question must use exactly four unique choices.
- Set correct_choice_index to the zero-based index (0-3) of the correct choice.
- Keep the requested exam, subject, topic, and difficulty faithful.
- Set explanation to an empty string. Explanations are generated by the separate explanation stage.
- A shortcut may be null when no useful shortcut exists.
- source_type must be "original" and source_reference must be null.
- For Maths, math_expression is REQUIRED and must evaluate exactly to the choice at correct_choice_index using ordinary arithmetic notation.
- For Maths, choose values with exact answers that can be represented by one of the four choices; avoid rounding and repeating-decimal ambiguity.
- For non-Maths questions, math_expression must be null.
- Do not put explanations or extra commentary outside the JSON object.

Return only the requested structured JSON.
""".strip()

    payload = {
        "systemInstruction": {
            "parts": [
                {
                    "text": (
                        "You are the question-writing engine for an Indian competitive-exam "
                        "education channel. Accuracy is more important than creativity. "
                        "Never invent an answer. Follow the requested schema exactly."
                    )
                }
            ]
        },
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {
            "responseFormat": {
                "text": {
                    "mimeType": "APPLICATION_JSON",
                    "schema": _RESPONSE_SCHEMA,
                }
            },
        },
    }

    response = None
    for attempt, delay in enumerate((0, 1, 2, 4)):
        if delay:
            time.sleep(delay)
        response = requests.post(
            _GEMINI_URL.format(model=GEMINI_MODEL),
            headers={
                "x-goog-api-key": GEMINI_API_KEY,
                "Content-Type": "application/json",
            },
            json=payload,
            timeout=60,
        )
        if response.status_code not in {429, 503} or attempt == 3:
            break

    assert response is not None
    if response.status_code != 200:
        raise RuntimeError(
            f"Gemini question generation failed ({response.status_code}): "
            f"{response.text[:500]}"
        )

    body = response.json()
    try:
        text = body["candidates"][0]["content"]["parts"][0]["text"]
        data = json.loads(text)
        items = data["questions"]
    except (KeyError, IndexError, TypeError, json.JSONDecodeError) as exc:
        raise RuntimeError("Gemini returned an invalid structured question response") from exc

    if len(items) != count:
        raise RuntimeError(
            f"Gemini returned {len(items)} questions; expected exactly {count}"
        )

    questions: list[Question] = []
    for item in items:
        item = dict(item)
        item["explanation"] = ""
        math_expression = item.pop("math_expression", None)
        correct_choice_index = item.pop("correct_choice_index", None)

        choices = item.get("choices")
        if (
            not isinstance(choices, list)
            or len(choices) != 4
            or not isinstance(correct_choice_index, int)
            or not 0 <= correct_choice_index < 4
        ):
            raise ValidationError("generated choices/correct_choice_index are invalid")

        item["correct_answer"] = choices[correct_choice_index]
        question = Question.from_dict(item)
        validate_question(question, math_expression=math_expression)
        questions.append(question)

    return questions
